### ISSUE TITLE
Procedurally generated maze map

### ISSUE THREAD

**Issue by deferred-impact** [deferred-impact/battledudes-issue-tracker#108]
Let's have it! A procedurally generated maze, different every time it is loaded. Made out of concrete walls akin to those in Heist. Twofold radially symmetrical to ensure fair gameplay in team gamemodes. Rather easy to implement, all things considered, with maze generation algorithms plentifully available on the interwebs. And guaranteed to stay fresh, pretty much forever!

**Comment by DisposableKatyusha** [comment]
yes

**Comment by Profugus1** [comment]
yes
but would take some time




and some players would find it annoying

YOU KNOW WHAT? THE MAP COULD BE THE BACKROOMS :))))))))))))
AND THERE COULD BE LIKE DIFFERENT ROOMS THAT ARE BACKROOMS THEMED
I'M JUST SO COOL GUYS

**Comment by deferred-impact** [comment]
Uhm... sure? I don't quite see how you would style it to obviously be the backrooms, beyond just making everything be made out of wood.

> but would take some time

Implementing a maze generator is remarkably easy. (Mainly because you can just borrow an existing one from the thousands of publicly available algorithms)

**Comment by Profugus1** [comment]
I mean implementing it into the game would take some time

Like the spawning position of the teams and the positions of certain points could potentially be buggy

**Comment by deferred-impact** [comment]
just don't implement bugs then 4head

**Comment by deferred-impact** [comment]
Oh, huh
