### ISSUE TITLE
Daily tasks

### ISSUE THREAD

**Issue by Haox09** [deferred-impact/battledudes-issue-tracker#113]
Battledudes should add daily tasks system to have more continued players. What i mean by this is that more player will play it everyday in result to the daily tasks. Daily tasks should consist of 2 tasks, one for coins and one gems. The reward will be different due to the difficulty of the tasks. Tasks examples: kill __ players with __ gun, get__ car kills, capture__ flags, gain__ xp etc. This can make players use different guns, do different things and have other goals than just winning and getting kills. Daily tasks would also boost the cosmetics economy as many of them cost many gems. However the max amount of reward everyday should be around 5 for gems and 30 for coins (meaning the max amount of gem one task that gives you is 5, which means hard task).

**Comment by Gregory-Y** [comment]
Good idea I support it because of the resemblance to amoug us. Also make the task difficulty visible.

**Comment by deferred-impact** [comment]
Yes but make sure impostors among us cannot do tasks.

**Comment by Profugus1** [comment]
Would make me play the game for 20 more minutes, then quit :)

**Comment by Profugus1** [comment]
but i support the idea :)

**Comment by deferred-impact** [comment]
Oh yeah, also this.
