### ISSUE TITLE
Adding more to the christmas chest

### ISSUE THREAD

**Issue by Haox09** [deferred-impact/battledudes-issue-tracker#115]
Literally this year's christmas chest is recycled from last year according to deffered. Many suggested Suasrunos should add more in the chest like christmas melee. Candy cane would be good, but still new idea is needed. Because this is a cosmetics suggestion i will not write more. I still hope Sasusrunas will see this and consider this

**Comment by Gregory-Y** [comment]
yes

**Comment by deferred-impact** [comment]
Dropping popular demand due to lack of a poll. If you think that label is applicable please post poll results from discord showing a majority of people in favor of this

**Comment by deferred-impact** [comment]
I don't... care about cosmetics. If you are upset because "waaaa there are no melees in this event waaaaaa only skins" then you're a bit dum dum

Give us a proper update with **actual gameplay changes**, please.

**Comment by Haox09** [comment]
among you then

**Comment by deferred-impact** [comment]
among us

**Comment by Haox09** [comment]
popular demand reached. Though Susrunasus added more hats but no melees. Should we close this issue? nah
