### ISSUE TITLE
(migrated) Weapon balance compendium:

### ISSUE THREAD

**Issue by deferred-impact** [deferred-impact/battledudes-issue-tracker#12]
tronald dump said:

> buff ak to 12.5 damage, maybe nerf falloff

> nerf M249 to 13 damage, nerf inital accuracy to 0.75 while perhaps keeping the accuracy after the decrease the same

> nerf sawed off to have 10 damage, make it a secondary to prevent extended mags from being used, maybe increase pellet count

> light sniper buff: idk, but imma think of soemthing for this

> buff SCAR bullet velocity to about 86 or so

**Comment by deferred-impact** [comment]
83 → 86 isn't a meaningful buff.

I don't like how extended mags work. I'll create a separate ticket for that. I'd still want Sawed Off to be in secondary slot, it just feels right; but i hate how whenever we have to remove extended mags from a weapon, we end up discussing whether we should move it to secondaries.

Light Sniper is a problem, yeah. Not sure what to do about it.

Everything else sounds cool and good

**Comment by deferred-impact** [comment]
Yours Truly said:

> give this a “weapons” tag

**Comment by deferred-impact** [comment]
SniperGaming said:

> Nerf sawed off so they fire their entire magazine simultaneously in one click I guess?

**Comment by deferred-impact** [comment]
No, the blam-blam is a rather unique feature (only crossbow and sawed off have that). Making this a single… burst? gun would remove that uniqueness

**Comment by Gregory-Y** [comment]
Yeah, I agree now that the scar falloff is kinda pointless. Maybe change the last part of it to buff scar to 13 damage, I think that would make it more worthwhile.

**Comment by Gregory-Y** [comment]
Also, since I made this originally, I would like to maybe make a few changes to it so can I please have perms to edit it? (or you could just write what i say if u think its good idk)

**Comment by deferred-impact** [comment]
Sadly i don't think i can give you perms to edit a specific message. Just send the new text in discord and i will update it

**Comment by deferred-impact** [comment]
@NOTGregory is this still relevant or should we close this? After the last AR rebalance i feel like we need to reconsider all our balancing suggestions

**Comment by Gregory-Y** [comment]
I'm trying to create an updated version but maybe we could close this issue and I could just write all my suggestions down on a new one.

**Comment by deferred-impact** [comment]
Sure, makes sense to me
