### ISSUE TITLE
Update to season 9 maybe

### ISSUE THREAD

**Issue by nlpha** [deferred-impact/battledudes-issue-tracker#121]
not something something recycle event idk

**Comment by Haox09** [comment]
Leave the Christmas be
People need to at least get all skins like comon
maybe in Feb

**Comment by deferred-impact** [comment]
> Leave the Christmas be People need to at least get all skins like comon maybe in Feb

LMAO

Yet another argument into the pile of "Why you must never tie updates to seasons", thanks Haox.

Apparently we're not getting a new gun because a bunch of people didn't get a chance to grind for a red colored hat?

**Comment by Haox09** [comment]
You are welcome
But if Sarunas have no idea what to update, he can't
He gives no leaks recently

**Comment by deferred-impact** [comment]
The dev has no idea what to update :skull: 

If only he had a place with 110 perfectly valid and well described suggestions

**Comment by Haox09** [comment]
If only he have time
well described maybe but not good enough? like the good ones are usually balance and you can't make a new season on that. maybe look deeper into the BD github iceberg

**Comment by deferred-impact** [comment]
> like the good ones are usually balance

There are 42 issues marked as "new gameplay content". Are you saying all of them are bad? :moyai:

**Comment by Haox09** [comment]
i said usually
like sarunas is more likely to add balance change than new gameplay content

**Comment by deferred-impact** [comment]
Oh yeah. This happened :moyai:
