### ISSUE TITLE
Payload timer should stop while the payload is moving forward

### ISSUE THREAD

**Issue by deferred-impact** [deferred-impact/battledudes-issue-tracker#129]
If the Payload is moving towards its destination, the timer should freeze. But if it is moving backwards or standing still, the timer decreases.

This would address the issue where sometimes in Payload the game is already lost, because the Payload barely moved during the entire match, yet you still have to play 4 minutes.

Of course, the timer would need to be adjusted so that the actual match time remains the same. Perhaps 5 minutes would work.

**Comment by Haox09** [comment]
Sounds like chess timers but this would make defending harder

**Comment by Gregory-Y** [comment]
Yes turn payload matches into chess games. I support this.

**Comment by deferred-impact** [comment]
> Sounds like chess timers but this would make defending harder

I don't think it changes anything about the difficulty. You still need to defend for N minutes before you are clear. All this does is remove the downtime which happens if it is no longer possible to push the payload to the finish line in time

**Comment by deferred-impact** [comment]
wowie!!11
