### ISSUE TITLE
Google Docs to compile list of ideas to send to sarunas

### ISSUE THREAD

**Issue by DisposableKatyusha** [deferred-impact/battledudes-issue-tracker#142]
found an old google docs in my drive of old ideas that we all intended to send to Sarunas by consensus
we can start one here with ideas from this github and send it to the whole community for their input + sarunas

**Comment by deferred-impact** [comment]
I don't... see how a Google Doc is superior to, y'know, github. With tags, built-in search and clear organization.

Shall we maybe write down these ideas on a piece of paper and send it to the dev via a messenger pigeon?

**Comment by Gregory-Y** [comment]
You can just put the stuff from the google doc here on github, and maybe split it into separate issues for different things like weapon balance, concepts, etc.

**Comment by DisposableKatyusha** [comment]
t
