### ISSUE TITLE
TDM scoring: Delta Scoring

### ISSUE THREAD

**Issue by deferred-impact** [deferred-impact/battledudes-issue-tracker#143]
Problems of current TDM scoring system:
 - battles between good teams end rapidly, because good teams kill each other quickly. Battles between bad teams end after 10 minutes, because noobs barely have any idea of what they are doing.
 - even if your team is now playing better than the enemy team (e.g. a good player joined your team, a good player left their team, people switched loadouts etc.), it's quite likely that you're just too far behind and cannot catch up to the enemy. E.g. if your team has 50 score and the enemy team has 80, to win you need to get 50 more points **faster** than the enemy gets 20.

If you agree with the above points (it would be insane not to), it is clear that TDM in its current state is flawed. But there is a simple solution.

Instead of tracking the absolute amount of kills, track the **Delta**. The Delta is the difference in the amount of kills between your team and the enemy team. If your team gets a kill, the Delta increases in your favor. If the enemy team gets a kill, the Delta increases in their favor.

Delta Scoring is an incredibly elegant solution. It automatically handles many use cases. If both teams are equally matched, the Delta will fluctuate around 0, and the game will end after 10 minutes. This is indeed what we want - **balanced matches are fun.**

At the same time, if one of the teams is simply better, we would want to end the game quickly, because destroying a team of noobs is arguably rather boring (there is no challenge). The Delta indeed unlocks an elegant approach to handling this, simply by the fact that **its growth rate is proportional to the difference in skill between teams.** So all we need to do is say, if Delta goes above 100 in either team's favor, the game ends and that team is the winner.

Thus, problems of current TDM scoring system are resolved:
 - currently, battles between good teams end rapidly, but battles between bad teams end after 10 minutes. The Delta fixes that partially. Battles between bad teams may still last for the whole 10 minutes, sure. But the key improvement is that battles between skillful teams will also last 10 minutes, as long as both teams are equally matched. The Delta Scoring eliminates the focus on the meaningless number of **total** kills, and instead focuses on the relevant number of, well, the Delta of kills.
 - even if your team is now playing better than the enemy team (e.g. a good player joined your team, a good player left their team, people switched loadouts etc.), it's quite likely that you're just too far behind and cannot catch up to the enemy. But, of course, with Delta Scoring that is no longer true. If a game ends prematurely due to Delta advantage, it is pretty much guaranteed that the winning team was the better team.

I can see many ways to improve this system, but even in this basic implementation, it is strictly better. It's also incredibly easy to implement.

**Comment by DisposableKatyusha** [comment]
yay
