### ISSUE TITLE
Scoring systems. Matches should never continue in an unwinnable state

### ISSUE THREAD

**Issue by deferred-impact** [deferred-impact/battledudes-issue-tracker#145]
Many scoring systems in this game are flawed, partially because once one of the teams gains enough of an advantage, it becomes effectively impossible to win for the other team, no matter how hard they try. This ticket is for tracking all issues regarding unwinnable situations due to scoring.

 - #129. Payload is unwinnable because the cart simply cannot reach the destination in the remaining time
 - #143. TDM is unwinnable because one of the teams is almost at the arbitrary 100 kills mark
 - #144. Control Points is unwinnable because holding 3 points is a disproportionally hard task

**Comment by DisposableKatyusha** [comment]
agree

**Comment by deferred-impact** [comment]
Ladies and gentlemen,

scoring systems.
