### ISSUE TITLE
I think someone suggested this before (idk, pls let me know): Frontline gamemode.

### ISSUE THREAD

**Issue by DisposableKatyusha** [deferred-impact/battledudes-issue-tracker#147]
How it works is that there are sets of objectives all around the map, and the objectives are all locked except for the first one, and if the first one is captured, the next one is unlocked, etc.

The teams are pitted together such that the the attacking team must capture all the objectives to win the game. The attacking team will have a set of spawn tickets (i.e 200 spawns to capture all obj.) that increases by a specific amount when a capture is successful (i.e 10-20 extra tickets, maybe 30)

The defending team will have infinite tickets such that if the attacking team runs out of tickets, they automatically win. There is no time limit.

I am aware that objectives can be captured in a short amount of time. How a map would work out in this gamemode can be given as such, example with Westlands map (may not actually work when put it like this, but gives you the idea):

![frontlines](https://user-images.githubusercontent.com/111546250/225431008-7e310caa-3d14-4b70-8621-124b97bb14ac.png)

**Comment by Gregory-Y** [comment]
war thunder reference

**Comment by deferred-impact** [comment]
No time limit sounds like trouble. What if both teams don't kill each other? A 2 hour long match is not ideal.

Spawns in this game are random, so i highly doubt you would observe much of a "frontline" forming.

Beyond these issues, it's not a terrible idea i guess, but personally i don't see anything truly exciting about it. In fact to me it looks like straight up just a reskin of Payload: an asymmetric gamemode with a moving objective, except, and indeed you yourself admit it, Frontline would be even more heavily stacked in attacker's favor.

**Comment by DisposableKatyusha** [comment]
This idea will not go anywhere.

**Comment by DisposableKatyusha** [comment]
h
