### ISSUE TITLE
Penetrating Sniper should gain double damage after 1 penetration

### ISSUE THREAD

**Issue by deferred-impact** [deferred-impact/battledudes-issue-tracker#150]
While it is undeniably unique, i am forced to agree with the popular sentiment that this new weapon is rather disappointing. Setting up one-shot-multikills in this game is not at all easy; people naturally tend to avoid walking in a line. And even once you do get the occasional penetrating multihit, it's likely inconsequential as you still need to deal with both players afterwards.

Let's reward multihits explicitly and impactfully. The change is simple. Once the bullet of this sniper deals damage to any enemy, it gains a 2x damage multiplier. This should be relatively easy to implement if my understanding is correct. It would also encourage people to go for multihits, and also make it more fun to fight this weapon, as it now becomes a very potent threat

**Comment by DisposableKatyusha** [comment]
it is already done and added.
