### ISSUE TITLE
Nerf ATV damage 

### ISSUE THREAD

**Issue by Haox09** [deferred-impact/battledudes-issue-tracker#158]
Right now using atv can give you a lot of kills and is basically braindead GTA simulator in the map Riverside, Crossroad, Westland with vehicles and Jailbreak. Concentrated in a small fight? A enemy ATV spawns out of nowhere. You tries to dodge it but it still kills you in 0.293 seconds of contact with the car. Then the enemy driver brooms out of there unhurt. Because the ATV is small and fast, it's hard to aim a rocket and I believe not many people want to waste their 1 shot weapon on a vehicle. Jeep damage can stay as it is, but because ATV is small, fast and furious, its damage should be reduced.

**Comment by Gregory-Y** [comment]
Agree. Also reduce the runover damage for the tank because it literally kills you instantly sometimes, like there's NOTHING you can do about it, it just kills you upon contact.
Also I do believe I have suggested this before in issue #75 but this is more specific so it's better.

**Comment by deferred-impact** [comment]
Reducing the ATV's speed is probably the better solution.

**Comment by Haox09** [comment]
![image](https://user-images.githubusercontent.com/117471088/234962064-7c832a2f-1228-4f5f-b474-21cbb8799b9a.png)

**Comment by deferred-impact** [comment]
Reducing the ATV's speed is probably still the better solution.

**Comment by Gregory-Y** [comment]
Car damage was nerfed.
