### ISSUE TITLE
Football-inspired gamemode

### ISSUE THREAD

**Issue by deferred-impact** [deferred-impact/battledudes-issue-tracker#165]
A better alternative to CTF.

CTF suffers from griefing. A red player can pick up the blue flag and then refuse to capture it, instead turtling in the corner. This ruins the game for everyone. No solutions so far have been proposed which solve it elegantly. (Perhaps there just aren't any good solutions)

A simple solution is to make it so that both teams can pick up the same flag. That is what Upload did, although Upload strayed further away from that classic CTF feel. If both teams can pick up the flag, then both teams are interested in grabbing it, making it practically impossible to hoard a flag.

The rules are literally football. There is one flag. The flag respawns in the middle. It can be picked up by either player. To score points, you must bring the flag to the other team's capture zone.

If you believe that the true CTF flavor requires 2 flags to be in play, then simply set the number of flags to 2 for this gamemode. It should work just as fine. As long as all flags can be captured by any team, no griefing problems arise.

In terms of effort, this should be implementable in 15 minutes. Most of the code can be copied from CTF.

**Comment by Haox09** [comment]
Which footbol club do you support?

**Comment by deferred-impact** [comment]
> Which footbol club do you support?

I don't care about football, lmao

**Comment by Gregory-Y** [comment]
Yes good idea it's more offensive than ctf which is good.

**Comment by DisposableKatyusha** [comment]
Shakhtar Donetsk #1 football team btw
we did it
