### ISSUE TITLE
Add assist XP (originally suggested by haox)

### ISSUE THREAD

**Issue by Gregory-Y** [deferred-impact/battledudes-issue-tracker#22]
Any amount of damage dealt to a player that's above 10 lends you assist XP if another user kills him. If a player deals above 45 damage to someone and another user gets the kill, they both get the kill. However, the guy who stole the kill only gets the amount of XP that corresponds to the amount of damage he dealt (which can't be less than 10, in which case the killcount goes up but no XP is gained).

Additionally, I propose making a system for allowing healing and ammo distribution to earn you XP, so I would say every time someone gains ammo (not for every bullet they receive, just every time their ammo counter increases), or heals with a medpack, they should gain 2 or so XP. In addition, I think for every repair to a friendly vehicle you do with a repair gun, you should gain 1 XP. (or maybe a little more idk)

**Comment by deferred-impact** [comment]
> Any amount of damage dealt to a player that's above 10 lends you assist XP if another user kills him. If a player deals above 45 damage to someone and another user gets the kill, they both get the kill.

Probably should track kills and assists separately, just to keep things understandable

> However, the guy who stole the kill only gets the amount of XP that corresponds to the amount of damage he dealt (which can't be less than 10, in which case the killcount goes up but no XP is gained).

Don't see why - even if i dealt 1 damage to finish off the enemy, i still did finish them off. And perhaps if i hadn't, they would've regenerated full HP as there was nobody else around to finish them. I would reward assists with a hardcoded amount, e.g. 25 XP

> Additionally, I propose making a system for allowing healing and ammo distribution to earn you XP, so I would say every time someone gains ammo (not for every bullet they receive, just every time their ammo counter increases), or heals with a medpack, they should gain 2 or so XP. In addition, I think for every repair to a friendly vehicle you do with a repair gun, you should gain 1 XP. (or maybe a little more idk)

Please open a separate issue for that

**Comment by Gregory-Y** [comment]
since artyom made a better version of this suggestion ill close it
