### ISSUE TITLE
Infinite Ammo

### ISSUE THREAD

**Issue by ghost** [deferred-impact/battledudes-issue-tracker#235]
Now, I don't know if this idea has already been thought of, or not, but I searched on the board and found nothing relative, so here we go. 

I believe ammo should be infinite, because it then no longer requires the ammo box. Do not misinterpret what I am saying, you will still be forced to reload, but you will have an infinite amount to reload to. 
It is rare, that you lose ammunition for every gun you have, making you weak to enemy fire. If you do live long enough for that to happen, you would be forced to go melee, or have an ammo pack to restore ammo. 

So if ammo was infinite, you wouldn't have to worry about the ammo box at all, you wouldn't be forced to use melee, and would have the ability to use other tools, like RP gun, Wall, etc. 

Now I understand, this would promote grenade spam, and would give RPG's infinite ammo. A simple solution to this, would be cooldown for someone to regain their throwables, perhaps a 10 second cooldown? I believe this has already been proposed by @deferred-impact, https://github.com/deferred-impact/battledudes-issue-tracker/issues/77, so it should work decently, combined with this implementation as well. 

Furthermore, other guns can be balanced (if needed), by a higher reload time, since they have infinite ammo. 
 
I still believe there would be many flaws for this idea, and want to discuss them, and balance it, as much as possible. Thus I would appreciate flaws to be discussed, so that the concept can be perfected.

**Comment by Haox09** [comment]
#136

**Comment by deferred-impact** [comment]
I actually think i prefer #164 at this point. It's a way to keep the ammo system, while still making it less frustrating.

I'm gonna close this issue because it's a duplicate. Want to discuss this? Pick your poison: #136 , #164

**Comment by ghost** [comment]
kk
