### ISSUE TITLE
Martyrdom

### ISSUE THREAD

**Issue by ghost** [deferred-impact/battledudes-issue-tracker#266]
This perk, will allow you to launch a frag grenade at the spot of your death, when you die. The grenade will have 2 seconds before it explodes. As a counter for using this, your respawn time will be doubled, if you die with Martyrdom activated.

**Comment by deferred-impact** [comment]
The issue i have with this idea is that it encourages suicide strategies. Is there much skill in simply running into a group of enemies and dying on purpose?

**Comment by ghost** [comment]
Yeah I've been trying to brainstorm a feature to come along with this idea, so that it prevents people from being able to die on purpose.
