### ISSUE TITLE
4 loadout slots is just not enough, man

### ISSUE THREAD

**Issue by deferred-impact** [deferred-impact/battledudes-issue-tracker#27]
I mean, it depends on your goals and playstyle, but 4 is not a large number. At least bump it to 6.

In an ideal world we would have the ability to store as many loadouts as we want to, and also have the option of naming each of them, for ease of searching

**Comment by Gregory-Y** [comment]
At first I thought you were saying 4 weapons in a loadout but yeah. I agree with this.

**Comment by deferred-impact** [comment]
![image](https://user-images.githubusercontent.com/87503574/187450654-3684a26b-8d02-4504-8ec2-307d5082fb90.png)

**Comment by DisposableKatyusha** [comment]
Wouldn't hurt
