### ISSUE TITLE
Make grenades deal damage to occupied hostile cars.

### ISSUE THREAD

**Issue by Gregory-Y** [deferred-impact/battledudes-issue-tracker#28]
Currently, throwing a frag grenade or sticky grenade at an enemy jeep or atv seems to deal no damage to the car or the player even if they are well within the grenade's aoe. I don't know what causes this issue, but it may have something to do with the cars moving and their speed affecting their hitboxes, idk. 

If this is fixed so that the car and/or the player take damage from grenades, then that would be great. Dealing with cars would become easier and they would be a bit less annoying to those who don't have rockets on them.

**Comment by deferred-impact** [comment]
Yes yes :+1:

**Comment by Gregory-Y** [comment]
I should also mention that this appears to only occur in moving cars, if someone's say stuck near a wall then a grenade will still damage the car.

**Comment by deferred-impact** [comment]
Um, no it won't. If someone is in a car, they and the car are invulnerable to grenades

**Comment by deferred-impact** [comment]
New season - implemented as requested. Closing
