### ISSUE TITLE
All projectiles should have a team colored tint

### ISSUE THREAD

**Issue by deferred-impact** [deferred-impact/battledudes-issue-tracker#34]
This is such an obvious improvement that it's honestly impressive how after 7 seasons this game still doesn't have it. Color enemy bullets and (most importantly) grenades red, color friendly bullets and grenades blue. It should be trivial to implement with like 5 lines of code.

**Comment by DisposableKatyusha** [comment]
wouldn't hurt to add

**Comment by deferred-impact** [comment]
![image](https://user-images.githubusercontent.com/87503574/187322950-63cf573a-cfbc-4bd4-8497-974da845eb1e.png)

Indeed, ack.

Hopefully season 8 sort of ack :flushed:

**Comment by deferred-impact** [comment]
Implemented. Only simple bullets for now - i.e. all AR, shotgun, sniper bullets, but not Flintlock, Crossbow nor Rocket shots. Sarunas expressed interest in making rockets tinted as well.

Closing this one. If someone wants to explicitly suggest specific non-tinted projectiles to be given the tint, create a new issue
