### ISSUE TITLE
Melee weapon bullet deflection.

### ISSUE THREAD

**Issue by Gregory-Y** [deferred-impact/battledudes-issue-tracker#42]
Allow melee weapons to deflect between 1 and 3 bullets if you attack at the right time. Comment if you guys think the bullets should deal damage to enemies if they actually reflect back into them.

**Comment by deferred-impact** [comment]
The main issue here? This counters snipers and snipers only. Any LMG user really won't mind 1-3 of their bullets being launched back at them - they have 47 more to offer.

It's also unrealistic (less realistic than #43), but as you know i am not a person who cares much about realism.

I just don't want any new features that make bulletspam *even stronger*, so as it is right now, i am against this one

**Comment by Gregory-Y** [comment]
Fair point, an ar or smg user could just bullshit his way through a storm of heavy sniper bullets before unloading at close range if he can deflect them.

**Comment by snipergamingop** [comment]
This is not a hack and slash game. You can't "deflect" or parry bullets LMAO

**Comment by deferred-impact** [comment]
Yeah, not a hack and slash game.

(except for all these shields which make ranged weapons obsolete and make melee combat optimal)

**Comment by Gregory-Y** [comment]
Bad idea

**Comment by Gregory-Y** [comment]
closing
