### ISSUE TITLE
WTF is going on with the new Ballistic Shield

### ISSUE THREAD

**Issue by deferred-impact** [deferred-impact/battledudes-issue-tracker#47]
It's ridiculously OP and needs to be addressed. With the right button presses, a player can ensure that the shield literally never disappears. This **should** be obviously problematic, yet the dev doesn't seem to see the problem(???)

Stop restoring the shield HP upon re-equipping it. Add a cooldown for the shield after it is destroyed - similar to how the deployable wall works.

**Comment by Gregory-Y** [comment]
Fully agree, no idea how Sarunas doesn't see this as an obvious problem. Yes, its difficult for the shield user to get kills, but its also almost impossible to kill them. It just becomes a tool for people to, well, avoid death.

**Comment by deferred-impact** [comment]
Addressed now as the shield now preserves HP and needs to be reloaded to fully restore it (which takes a while).

Granted, certain aspects of the fix could be better. Specifically, the shield should not be usable during the reload. Right now a kind of (much weaker) cycling can still happen, if you start reloading as soon as you get the shield. Unsurprisingly, it mostly counters the HS:

time for full HS mag fired: 2 seconds
time for HS reload: 2.3 seconds

time for shield reload: 4 seconds
time for shield equip: ~0.7 seconds

time the shield user is vulnerable to HS fire: 0.4 seconds

Still, the big problem has been fixed; shield users are no longer invincible, you just need to have enough firepower
