### ISSUE TITLE
Buff crossbow damage to ensure 2 shot kill

### ISSUE THREAD

**Issue by deferred-impact** [deferred-impact/battledudes-issue-tracker#55]
Ultimately this would be addressed by #21, but that one takes more effort to implement. And, for that matter, how is it fair that Flintlock kills in 2 shots yet Crossbow (sometimes) needs 3?

**Comment by Gregory-Y** [comment]
I think this should be closed because crossbow was buffed to deal 30 damage, which is enough to kill a player including kevlar users.
