### ISSUE TITLE
Get the dev to explain why 1912 pistol has higher accuracy than Flintlock

### ISSUE THREAD

**Issue by deferred-impact** [deferred-impact/battledudes-issue-tracker#56]
Look i don't mind it having such high accuracy, if anything i prefer high accuracy bulletspam to low accuracy bulletspam, i just want to understand the reasoning here

**Comment by Gregory-Y** [comment]
bekuz flint sux!!!!!
1912 has higher accuracy because if it has low accuracy then the low accuracy with the already unreliable damage and fire rate would make it useless. Anyway I dont think 1912 being more accurate than flint is really a big problem because of flint's projectile size.

**Comment by deferred-impact** [comment]
Inaccuracy always matters. It puts a cap on the skill any player can achieve. If your shots do not go where you tell them to go, you're not gonna play well. #29 addresses that.

But if we *really* must have sniper weapons with shit accuracy, can we at least ensure that they have the *highest* accuracy **among** all g**u**n**s**

**Comment by Gregory-Y** [comment]
amogüüs
I mean I don't disagree with the suggestion I just don't think its that important.

**Comment by deferred-impact** [comment]
If it's not that important then let's just do the change then, it takes probably less than 5 minutes, just a stats change :moyai:

**Comment by deferred-impact** [comment]
Ah, but i remember this one.
