### ISSUE TITLE
Many walls, zero roofs. Request for a new map

### ISSUE THREAD

**Issue by deferred-impact** [deferred-impact/battledudes-issue-tracker#59]
I like walls.

I hate roofs.

I'm sure i'm not the only one.

Make it kind of like a maze of some kind. I think it would be a good and fun addition to the game, and one that would offer unique gameplay (highly tactical and skillful, arguably).

**Comment by Gregory-Y** [comment]
I like the idea of that. Could make it like a military cqb training area or something with all the wooden boards and stuff.

**Comment by Profugus1** [comment]
A maze map could be fun, though it could be extremely annoying if the maze was too big. Plus, if there were capture points, they would only get captured if some random dude knew exactly where they were going.

**Comment by deferred-impact** [comment]
Idk about it being annoying - one of the key features of this game is the ability to just blast through any annoying wall with any weapon.

> if some random dude knew exactly where they were going.

people would learn the layout quite quickly, + the map exists.

*That said*, perhaps the maze should be procedurally generated? Now, **that** would be exciting!

**Comment by snipergamingop** [comment]
Make it so it have decent spaces between walls to dodge bullets (perhaps also make the map randomly generated itself?)

**Comment by deferred-impact** [comment]
I'm thinking of 3-5 squares wide corridors built out of concrete walls (the ones used for Heist vault room and Islands beach bunkers). I think this would be enough space for dodging, although thin enough to make dodging hard (and, thus, interesting)

**Comment by snipergamingop** [comment]
> I'm thinking of 3-5 squares wide corridors built out of concrete walls (the ones used for Heist vault room and Islands beach bunkers). I think this would be enough space for dodging, although thin enough to make dodging hard (and, thus, interesting)

Would that encourages bulletspamming?

**Comment by deferred-impact** [comment]
Eh, idk. Hard to say. Perhaps a sniper is in fact superior in a long corridor. If your AR is spraying so wide that the bullets are hitting the sides of the corridor, you're not using your entire DPS.

Plus, in a maze with many corners, snipers and shotguns (and any other single fire crap) should dominate. An assault rifle is powerful, but only if it can continuously spray an enemy uninterrupted. Add in a wall inbetween and suddenly the assault rifle user has to reconsider.

**Comment by deferred-impact** [comment]
Okay
