### ISSUE TITLE
Make melee 1 shot the shield

### ISSUE THREAD

**Issue by snipergamingop** [deferred-impact/battledudes-issue-tracker#64]
Yes sound dumb but let me explain. When you use melee weapon you are vulnerable to ranged weapons, and now with shield included, melee have more usefulness now. Make it oneshot shields so you would force them into switching back to sidearm. This would pair very well with #58 and would solve the problem of shield cycling (partially at least)

**Comment by deferred-impact** [comment]
To me, it makes little sense.

1. We already have a weapon which insta-destroys the Shield - that's our beloved Rocket Launcher. To me that feels like a very balanced interaction. It's not easy to hit a player with the rocket - but if you do, you are rewarded by instantly removing 120 HP from them (which is quite an amount for any other gun to deal with). On the other hand, the Shield user also doesn't feel cheated - sure, they lost the Shield, but at least they avoided immediate death.

2. Melee is free. It has infinite ammo and better movement speed. It also does not take up a slot that could be spent on something else. Why should it then have the same effect as the Rocket, while taking much less effort to execute?

3. Melee has an advantage over the Shield. Melee is fast movement, Shield is extra HP. And again, Melee doesn't use up a slot.

4. This change would completely discourage Shield users from ever using it offensively. Slowing down the pace of the game even more and making it incredibly defense-biased. Great! Everybody is a turtle.

**Comment by Gregory-Y** [comment]
Yeah no this doesn't seem like a good idea because of the reasons deferred impact stated above. I think shield should serve more as a counter to melee (or at least a means of defense against it) than the other way around. Now that its been nerfed, there's plenty of ways to delete a shield and force someone onto their back foot, insta-deleting the shield with melee would make the shield utterly useless.

**Comment by Gregory-Y** [comment]
Oh and you mentioned shield cycling which is already fixed.

**Comment by Gregory-Y** [comment]
I'm pretty sure this won't be a good addition and we already have the suggestion for shield not working during reload as a potential nerf.

**Comment by Gregory-Y** [comment]
should probably close as not planned instead
