### ISSUE TITLE
Rocket-only gamemode

### ISSUE THREAD

**Issue by deferred-impact** [deferred-impact/battledudes-issue-tracker#68]
I was honestly surprised to find out that people actually are interested in this, unironically.

![image](https://user-images.githubusercontent.com/87503574/189523852-0aeb0e95-a9f1-4f36-9e1d-03d34a2abcc4.png)

Obviously i would love such a mode, and i also honestly think it would be a good addition to the game.

 - it's incredibly easy to implement (mostly reusing code from GunGame)
 - it would offer very unique gameplay
 - instakilling someone does yield a dopamine surge that the usual bulletspam doesn't
 - it would look epic and ridiculous

However, it does have some flaws
 - it would be higher skill on average than the normal gameplay. (The Rocket does need to be aimed properly)
 - all types of snipers (including the Rocket) are incredibly tedious to use on mobile. (#60 would address it)
 - perhaps most importantly, a gamemode only featuring the Rocket would be somewhat bland. Ideally we would have different Rocket Launcher types with various gimmicks, but as of right now, we do not have such options. (Unless you want to argue that the Flintlock is a Rocket Launcher)

Still, i think it would be a worthwhile addition. We can always remove the gamemode afterwards if people decide it's not fun.

The ammo should be infinite in this mode

**Comment by DisposableKatyusha** [comment]
I am for this.

**Comment by Gregory-Y** [comment]
yes

**Comment by deferred-impact** [comment]
![image](https://user-images.githubusercontent.com/87503574/192087063-7b5fdcc1-f8a8-4836-a5c3-1dfb7fccc63b.png)

**Comment by deferred-impact** [comment]
Imagine???
