### ISSUE TITLE
Nerf Car damage

### ISSUE THREAD

**Issue by Gregory-Y** [deferred-impact/battledudes-issue-tracker#75]
![image](https://user-images.githubusercontent.com/68972578/190641690-1a7131a7-5937-4dc6-8324-8ef3054f086d.png)
Cars have been notorious for running people over. Making them susceptible to grenades did not do enough to make it easier to fight cars. At least a slight nerf to the runover damage would be good.

**Comment by deferred-impact** [comment]
Well, to be fair, such kills are a bit cheap and low skill. So i suppose i'm not against this.

**Comment by DisposableKatyusha** [comment]
yes

**Comment by Gregory-Y** [comment]
car damage was nerfed

**Comment by Gregory-Y** [comment]
woops i meant to close this
