### ISSUE TITLE
"Rocket Launcher only" mode

### ISSUE THREAD

**Issue by deferred-impact** [deferred-impact/battledudes-issue-tracker#84]
![image](https://user-images.githubusercontent.com/87503574/192048949-924e20d6-7634-4c6e-96b8-979d592a2d7b.png)

**Comment by deferred-impact** [comment]
Little effort needed because you can just copy the code from Gun Game

**Comment by Gregory-Y** [comment]
wHy NoT JuST rE-aDd TEnk bAtTle!!!!!!!!!!

**Comment by Gregory-Y** [comment]
Also I just realized this and #68 are duplicate issues so

**Comment by deferred-impact** [comment]
duplicate
