### ISSUE TITLE
(migrated) Copy blue Impulse Grenades from ZR

### ISSUE THREAD

**Issue by deferred-impact** [deferred-impact/battledudes-issue-tracker#9]
The trickshot potential is immense. Personally for me these grenades were the highlight of that game. Adding them to BD would greatly diversify the gameplay and offer further strategic opportunities.

Not sure if red Impulses are worth copying, though.

**Comment by deferred-impact** [comment]
tronald dump said:

> Not very original but maybe with a few twists, we could implement a weapon thats a little similar to the impulse grenade. I'll see if I can think of something epip.

**Comment by deferred-impact** [comment]
Ideas don't need to be original. A good idea should propagate throughout gaming.

If you needed this game to be 100% original, it literally wouldn't exist. Kill Confirmed, Hardpoint, CTF, Flashbangs, Trophy System, literally all perks. It's a copy of Battleduty Call of Field, don't you know?

**Comment by deferred-impact** [comment]
Yours Truly said:

> give this a "weapons" tag(sry for the spam since I said this in a lot of different suggestions)

**Comment by TheGoldenGemXD** [comment]
An impulse grenade jump can be simulated using regular frag grenades and going to the very edge of the blast radius, while it is hard to pull off, it does have immense tactical use as a getaway, and a method to maneuver during a gun fight. I think if the blast radius of the impulse was like a frag grenade and was stickable, it’d be perfect.

**Comment by Gregory-Y** [comment]
@TheGoldenGemXD Late reply but you bring up a good point, when an explosive detonates near you, you get pushed away. However, I think that functionality is best reserved for an impulse grenade which specialized in pushing enemies away. I don't think you should have to rely on finding the right distance from a grenade to be able to get a speed boost; an impulse grenade would be much better suited for that role.

**Comment by deferred-impact** [comment]
Frag grenades aren't designed for pushing players. Whenever it happens, it's unintentional - not necessarily a bug, i guess, but a weird outcome nevertheless. And certainly not something you could pull off reliably. The room for error is to be measured in decipixels.

The impulse grenade would inherently be balanced (if you managed to hit an impulse + sniper trickshot, you would've managed to hit a frag) and would add a lot of gameplay variety.

The only concern i have at this moment is people jumping out of buildings via the use of such grenades in order to surprise players. However, this isn't impossible to fix. For example, you could make players, who are holding an impulse grenade, glow through roofs.
